package com.sampark.PMS;

public class PMSConstants {
	
	public static final String IN_PLANNING = "In Planning";
	public static final String IN_REVIEW = "In Review";
	public static final String IN_PROCESS = "In Process";
	public static final String OK = "OK";
	public static final String NEW_KRA = "NEW";
	public static final String OLD_KRA = "oldKRA";
	public static final String KRA_SCREEN = "kraScreen";
	public static final String GOAL_SETTING = "Goal Setting";
	public static final String GOAL_APPROVAL = "Goal Approval";
	public static final String MID_TERM_REVIEW = "Mid Term Review";
	public static final String YEAR_END_ASSESSMENT = "Year End Assessment";
	public static final String ASSESSMENT_APPROVAL = "Assessment Approval";
	public static final String ROLE_HR_HEAD = "HEAD HR";
	public static final String ROLE_CEO_AND_ED = "CEO";
	public static final String  CLOSED_WITH_MANAGER ="CLOSED WITH MANAGER";
	public static final String PENDING_WITH_EMPLOYEE ="PENDING WITH EMPLOYEE";
	public static final String PENDING_WITH_MANAGER ="PENDING WITH MANAGER";
	public static final String EMPLOYEE_APPRAISAL_APPROVAL ="EMPLOYEE APPRAISAL APPROVAL";
	public static final String EMPLOYEE_APPRAISAL_REJECT ="EMPLOYEE APPRAISAL REJECT";
	public static final String MANAGER_APPRAISAL_APPROVAL ="MANAGER APPRAISAL APPROVAL";
	public static final String MID_FIRST_LEVEL_MANAGER_APPRAISAL_APPROVAL ="MID FIRST LEVEL MANAGER APPRAISAL APPROVAL";
	public static final String MID_FIRST_LEVEL_MANAGER_APPRAISAL_REJECTED ="MID FIRST LEVEL MANAGER APPRAISAL REJECTED";
	public static final String MID_SECOND_LEVEL_MANAGER_APPRAISAL_APPROVAL ="MID SECOND LEVEL MANAGER APPRAISAL APPROVAL";
	public static final String FINAL_FIRST_LEVEL_MANAGER_APPRAISAL_REJECTED ="FINAL FIRST LEVEL MANAGER APPRAISAL REJECTED";
	public static final String FINAL_SECOND_LEVEL_MANAGER_APPRAISAL_REJECTED ="FINAL SECOND LEVEL MANAGER APPRAISAL REJECTED";
	public static final String FINAL_EMPLOYEE_APPRAISAL_APPROVAL ="FINAL EMPLOYEE APPRAISAL APPROVAL";
	public static final String FINAL_SECOND_LEVEL_MANAGER_APPRAISAL_APPROVAL ="FINAL SECOND LEVEL MANAGER APPRAISAL APPROVAL";
	public static final String NEW_EMPLOYEE="NEW EMPLOYEE";
	public static final String EMPLOYEE_APPRAISAL = "EMPLOYEE APPRAISAL";
	public static final String SEND_FORM = "pms@herofutureenergies.com";
	public static final String SEND_FORM_PASSWORD = "Gus171930";
	public static final String INPUT_OPTION_ALL = "ALL";
	public static final String DATE_FORMAT = "dd/MM/yyyy";
	public static final String TIME_FORMAT = "HH24:mi:ss";
	public static final String TIME_FORMAT_JAVA = "HH:mm:ss";
	public static final String USER_EMPLOYEE = "EMPLOYEE";
	public static final String USER_HR = "HRUSER";
	public static final String USER_SUPER = "SUPERUSER";
	public static final String SPLIT_TEXT = "@";
	public static final String USER_TRAINEE = "TRAINEE";
	public static final String USER_HOD = "HOD";
	public static final String USER_ADMIN = "ADMIN";
	public static final String USER_MANAGER = "MANAGER";
	public static final String USER_GUEST = "GUEST";
	public static final String BUTTON_APPROVED = "APPROVED";
	public static final String BUTTON_REJECTED = "REJECTED";
	public static final String BUTTON_SAVE = "SAVE";
	public static final String BUTTON_SUBMIT = "SUBMIT";
	public static final String USER_CONTACT = "CONTACT";
	public static final String NULL_VALUE = "NULL";
	public static final String USER_CLIENT = "CLIENT";
	public static final Integer STATUS_ACTIVE = 1;
	public static final Integer STATUS_DELETED = 0;
	public static final Integer STATUS_SUCCESS = 1;
	public static final Integer STATUS_FAILED = 0;
	public static final Integer STATUS_PENDING = 2;
	public static final Integer DEPARTMENT_PARAMETERS_ID = 1;
	public static final Integer DESIGNATION_PARAMETERS_ID = 2;
	public static final Integer QUALIFICATION_PARAMETERS_ID = 3;
	public static final String FIRST_LEVEL_EMPLOYEE = "FIRST LEVEL EMPLOYEE";
	public static final String SECOND_LEVEL_EMPLOYEE = "SECOND LEVEL EMPLOYEE";
	public static final String FIRST_LEVEL_MANAGER = "FIRST LEVEL MANAGER";
	public static final String SECOND_LEVEL_MANAGER = "SECOND LEVEL MANAGER";
	public static final String APPRAISAL_MID_YEAR = "MID YEAR";
	public static final String APPRAISAL_FINAL_YEAR = "FINAL YEAR";
//	public static final  String BASE_PATH ="D:/lenovo/PMS/src/main/webapp/resources/common/documents";
//	public static final  String IMAGE_BASE_PATH ="D:/lenovo/PMS/src/main/webapp/resources/common/documents/";
//	public static final  String DOC_BASE_PATH ="D:/lenovo/PMS/src/main/webapp/resources/common/documents/";
//	public static final  String BASE_URL ="http://localhost:8080/PMS";
	public static final  String IMAGE_BASE_PATH ="/home/hero/pms/images/";
	public static final  String DOC_BASE_PATH ="/home/hero/pms/documents/";
	public static final  String BASE_URL = "https://pms-hfe.com/PMS";
	public static final  String BLANK_DOC = "/pms/images?image=null&folder=document";
	public static final String FIRST_LEVEL_MANAGER_APPRAISAL_APPROVAL = "FIRST_LEVEL_MANAGER_APPRAISAL_APPROVAL";
	public static final String SECOND_LEVEL_MANAGER_APPRAISAL_APPROVAL = "SECOND_LEVEL_MANAGER_APPRAISAL_APPROVAL";
	
	
//	public static final  String IMAGE_BASE_PATH ="/home/malaya/PMS/images";
//	public static final  String EMAIL_CONTENT_NEW_EMPLOYEE = "<a href='#'><h3 style='background-color:blue; color:white; padding:25px; text-align:center;'> Click Here For Account Validation</h3></a>";
	
}
